### ISSUE TITLE
no left to right swing

### ISSUE THREAD

**Issue by cewbdex** [sockless-coding/panasonic_cc#127]
I don't have an option to control left-right movement, would it be possible to enable it? In Panasonic app it's working properly. Both units are CS-Z35VKEW

![Screenshot_2023-09-22-16-24-23-090_io homeassistant companion android](https://github.com/sockless-coding/panasonic_cc/assets/9021297/13da2578-625a-405a-baac-5614c00b0e08)
![Screenshot_2023-09-22-16-24-32-380_com panasonic ACCsmart](https://github.com/sockless-coding/panasonic_cc/assets/9021297/409e7d7f-b552-41ef-abcf-081485a86133)

**Comment by amund7** [comment]
+1, I have a HZ25XKE

**Comment by sockless-coding** [comment]
Unfortunately, the default card doesn't support for multiple swing modes. And the horizontal swing modes attributes were lost due to changes, but that has been fixed by #145 
There is also an extra service `panasonic_cc.set_horizontal_swing_mode` that lets you change the horizontal mode.

**Comment by amund7** [comment]
Great! Then I'll wait for the next release, thanks for the effort!

**Comment by codyc1515** [comment]
It looks like the integration does not [follow the spec for Swing Modes](https://developers.home-assistant.io/docs/core/entity/climate/#swing-modes) which specifies `SWING_OFF`, `SWING_VERTICAL`, `SWING_HORIZONTAL` & `SWING_BOTH`. Seems like a trade-off. The integration currently lets you specify more granular but because of that you can only set one direction.

**Comment by sockless-coding** [comment]
Horizontal swing has been moved to separate select control in v1.1.0
