### ISSUE TITLE
Update pcomfortcloud to 0.0.17 (to fix 403 Forbidden)

### ISSUE THREAD

**Issue by martinwahlstrom** [sockless-coding/panasonic_cc#17]
Hi,

Seems as Panasonic changed something, and there is a fix available in pcomfortcloud 0.0.17:
https://github.com/lostfields/python-panasonic-comfort-cloud/issues/33

Not skilled enough to do anything myself here :)

regards Martin/

**Comment by omnix1** [comment]
I tried to do a pull request for this but I don't think I have access to do that :)
Until the fix is out, you can manually update the `config/custom_components/panasonic_cc/manifest.json` from `"requirements": ["pcomfortcloud==0.0.16"]` to `"requirements": ["pcomfortcloud==0.0.17"]` and restart Home Assistant. That solved my issues.

**Comment by SeraphimSerapis** [comment]
> I tried to do a pull request for this but I don't think I have access to do that :)
> Until the fix is out, you can manually update the `config/custom_components/panasonic_cc/manifest.json` from `"requirements": ["pcomfortcloud==0.0.16"]` to `"requirements": ["pcomfortcloud==0.0.17"]` and restart Home Assistant. That solved my issues.

Done ;-) Fingers crossed this gets merged soon.

**Comment by martinwahlstrom** [comment]
Thx! That did the trick!

**Comment by sockless-coding** [comment]
Merged and released a new version with the fix.
