### ISSUE TITLE
8/15 C mode

### ISSUE THREAD

**Issue by Tipmanfrank** [sockless-coding/panasonic_cc#177]
I have installed this integration and I already love it. But I am missing one mode from my Panasonic NZ25YKE. This device has a 8-15 degrees C mode. I can't find this mode in the integration. Will it be possible to have this mode added to this project?

Best regards Frank Larsen

**Comment by ttjorvi** [comment]
Second this. I would really like this feature

**Comment by johanolde** [comment]
Me too!

**Comment by sockless-coding** [comment]
v1.0.49 has a +8/15 preset

**Comment by KDanielK** [comment]
I think something broke due to this, not sure if its connected though. When I try to change from boost to normal or reverse nothing happens. This is the only command sent to the cloud in the log, not sure if its missing something in the parameters since nothing happens. 
2024-06-28 08:34:42.580 DEBUG (MainThread) [custom_components.panasonic_cc.panasonic] Set Luftvärmepump ecomode boost
2024-06-28 08:34:44.028 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] POST url: https://accsmart.panasonic.com/deviceStatus/control, data: {'deviceGuid': 'CS-HZ35UKE+4939804724', 'parameters': {'operate': 1}}, response: {"result":0}

**Comment by sockless-coding** [comment]
Should be fixed in v1.0.50

**Comment by Tipmanfrank** [comment]
Hi
Regarding 1.0.54:

I have been testing 8/15 mode. The scale changes to 8-15 degrees. All fine.

But I can’t get back to Heat mode and have a scale above 16 degrees. When I change Preset modes to None then it jumps to 8/15. From the app (see attachment), the 8/15 is more like a hvac_mode.

![IMG_2237](https://github.com/sockless-coding/panasonic_cc/assets/85414873/d1b20306-471a-4a14-9fc3-8a2d7e8f4642)
Conclusion: 8/15 seems to work but I can’t get away from this mode.

**Comment by sockless-coding** [comment]
The problem is that HA seem to read the min max once, and the +8/15 changes it and it should change back when you exit the mode but the UI doesn't seem to register the change.

**Comment by Tipmanfrank** [comment]
Can you you figure out a solution or a workaround?Venlig hilsenFrankDen 29. jun. 2024 kl. 16.27 skrev Jimmy Everling ***@***.***>:﻿
The problem is that HA seem to read the min max once, and the +8/15 changes it and it should change back when you exit the mode but the UI doesn't seem to register the change.
