### ISSUE TITLE
fan_only missing in 1.1.0

### ISSUE THREAD

**Issue by hankys** [sockless-coding/panasonic_cc#259]
Hello,

the option "fan_only" is missing since update to 1.1.0

**Comment by ParadiseComputing** [comment]
Hello.
Many thanks for keeping this intergration updated - really approciate the work.
Along with the "fan_only" missing, since updating to 1.1.0, the heat/cool option also fails - though other modes work fine.
Have downgraded to 1.0.58 for now - but can update again if logs are needed.
Thanks

**Comment by sockless-coding** [comment]
Hello, 
v1.1.0 now checks the supported features reported by the API, does your devices support the fan only mode (is it available in the app)?

**Comment by sockless-coding** [comment]
I've fixed the heat/cool mode in v1.1.1

**Comment by hankys** [comment]
I cannot select it on the remote, like i cannot select it the app.

I also did select fan mode in HA and set temperatur so 16. There is nothing cooling, which was the last selected mode before fan mode. It's just moving the air in fan mode.
I can also select different fan speeds in fan mode.

**Comment by sockless-coding** [comment]
Try setting the temperature to above ambient, Fan has value 4 and Heat 3... so it might put it in heating mode.
If it's not turning out any heat, I could add an override setting to force enable fan only.

**Comment by heldchen** [comment]
same issue here.ä: fan_only is now missing for both my HVAC systems. the panasonic app shows fan_only as nanoex mode instead of a dedicated fan mode, but it still worked perfectly when toggled in the HA plugin.

so while technically true that the api response does not directly expose the fan only capacity, it still supported by the HVACs. if you are hesitant to automatically have fan only mode supported, maybe it could be a per-device toggle to enable it as feature override?

**Comment by sockless-coding** [comment]
Hmm, seems strange that Panasonic is reporting the feature as unavailable, and it's still working...
I'll just ignore their "fan only" feature check and have fan only added to all devices.

**Comment by sockless-coding** [comment]
Try v1.1.2

**Comment by heldchen** [comment]
I completely agree. I think it is a limitation of their api: in Bluetooth mode, one of my AC has a lot more settings & options (f.e. individual duct control of the cassette hvac). on the other hand, that HVAC does not support presets through the api at all (something the plugin does not yet replicate properly btw, but I did not yet figure how to detect this in the device api response - once I do I will add an issue with the necessary details)

**Comment by heldchen** [comment]
> Try v1.1.2

works great, thanks!

there is a small display regression - the friendly name for the mode is not used in the control components - I think the values are not mapped due to an added "°C":

![Screenshot_20240806-215900](https://github.com/user-attachments/assets/dbf657b3-6eb3-487d-ad3e-153ff1756229)
![Screenshot_20240806-215836](https://github.com/user-attachments/assets/01e9447d-69cc-4ed7-92df-860957035eb7)

**Comment by sockless-coding** [comment]
I've noticed those °C too, I have no idea where they are coming from. If you look at the attributes of the entity, they are not there.
The only thing that might be because I've added a translate key so I can override the visual values of the other options. But mode should be using the defaul.

**Comment by heldchen** [comment]
[other integrations](https://github.com/home-assistant/core/blob/abaac519c9ceb8a54bfd2bc9344841b6c0382673/homeassistant/components/climate/services.yaml#L108) have "hvac_mode" set ton "translation_key: hvac_mode" in services.yaml, maybe something similar would fix the issue?

**Comment by heldchen** [comment]
@sockless-coding I found the issue and created a PR for it: https://github.com/sockless-coding/panasonic_cc/pull/263

**Comment by hankys** [comment]
> Try v1.1.2

Works fine !
Thank you very much
