### ISSUE TITLE
Energy Monitor

### ISSUE THREAD

**Issue by glazeddonut** [sockless-coding/panasonic_cc#328]
### Problem Description

Is it possible to retrieve the energy data (kWh usage) from the API?

### Solution Description

I would love to be able to create an utility meter on the total energy (kWh) usage.

**Comment by sockless-coding** [comment]
@glazeddonut Hi, you can enable the energy sensors in the configuration of the integration:
![image](https://github.com/user-attachments/assets/5d62c4b6-8fc6-4c68-8f78-53225a0a9aa0)
There is no total energy sensor since the api doesn't provide a total value and creating one would require a lot of api calls.
But you can use the [Utility Meter](https://www.home-assistant.io/integrations/utility_meter/) or [Energy Meter](https://github.com/zeronounours/HA-custom-component-energy-meter) to create a running total in HA.

**Comment by pajikcz** [comment]
Hi, i have just bought air condition CS-TZ25ZKEW WiFi and all is integrated well, inc. enabled energy sensors. But the refresh rate of energy sensors doesnt seem to be working, i need to need wait tens of minutes to get new data.  E.g. temp values are live updated, but not energy ones. Any suggestion? thank you

**Comment by pajikcz** [comment]
@sockless-coding  thank you for the reply.
